Repository Taiwan-Ebook-Lover/TaiwanEbookSearch-API, pull requests merged in 2021-05, with the labels that each got.

#21 Feat v0.1/mongo to firestore
  .gitignore
  package-lock.json
  package.json
  src/db.ts
  src/firestore.ts
  src/index.ts
  src/interfaces/book.ts
  src/interfaces/bookstore.ts
  src/interfaces/firestoreBookstore.ts
  src/routers/search.ts
  src/stores/bookWalker.ts
  src/stores/booksCompany.ts
  src/stores/hyread.ts
  src/stores/index.ts
  src/stores/kobo.ts
  src/stores/playStore.ts
  src/stores/pubu.ts
  src/stores/readmoo.ts
  src/stores/taaze.ts
  tsconfig.json
Labels: done, enhancement

#23 chore: add lint workflow
  .editorconfig
  .env.example
  .github/workflows/code-check.yml
  .husky/.gitignore
  .husky/pre-commit
  .idea/prettier.xml
  .prettierrc
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  src/auth/serviceAccount.json.example
  src/bot.ts
  src/firestore.ts
  src/index.ts
  src/routers/bookstores.ts
  src/routers/searches.ts
  src/stores/bookWalker.ts
  src/stores/booksCompany.ts
  src/stores/hyread.ts
  src/stores/kindle.ts
  src/stores/kobo.ts
  src/stores/playStore.ts
  src/stores/pubu.ts
  src/stores/readmoo.ts
  src/stores/taaze.ts
Labels: enhancement

#25 fix(bookstore): search issue without cookie in hyread
  src/stores/hyread.ts
Labels: bug
